# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 04:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.UUIDField()),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=128)),
                ('attach_point', models.PositiveSmallIntegerField()),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OutfitRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_time', models.DateTimeField(auto_now_add=True)),
                ('request_prim', models.UUIDField()),
                ('request_slurl', models.URLField()),
                ('corrected', models.BooleanField()),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BodyPartMatcher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator_key', models.UUIDField()),
                ('name_matcher', models.CharField(max_length=64)),
                ('description_matcher', models.CharField(default='%', max_length=128)),
                ('attach_point_min', models.PositiveSmallIntegerField(default=0)),
                ('attach_point_max', models.PositiveSmallIntegerField(default=100)),
                ('body_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.BodyPart')),
            ],
        ),
        migrations.AddIndex(
            model_name='bodypartmatcher',
            index=models.Index(fields=['creator_key'], name='body_detect_creator_69a9f8_idx'),
        ),
    ]
