# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-26 04:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sl_profile', '0001_initial'),
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayLedger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_day', models.DateField()),
                ('sale_count', models.PositiveIntegerField()),
                ('sales_income', models.PositiveIntegerField()),
                ('avg_sale_revenue', models.FloatField()),
                ('budgeted_expense', models.IntegerField()),
                ('withholding', models.PositiveIntegerField()),
                ('total_profit', models.PositiveIntegerField()),
                ('unique_seller_count', models.PositiveIntegerField()),
                ('unpack_count', models.PositiveIntegerField()),
                ('unique_outfit_count', models.PositiveIntegerField()),
                ('garment_count', models.PositiveIntegerField()),
                ('dividend_per_garment', models.PositiveIntegerField()),
                ('operator_dividend', models.PositiveIntegerField()),
                ('unique_outfits_to_date', models.PositiveIntegerField()),
                ('garments_to_date', models.PositiveIntegerField()),
                ('sales_to_date', models.PositiveIntegerField()),
                ('creator_dividend_to_date', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GarmentDistribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.PositiveSmallIntegerField()),
                ('collaborator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sl_profile.Resident')),
                ('garment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.Garment')),
            ],
        ),
        migrations.CreateModel(
            name='MonthLedger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_day', models.DateField()),
                ('last_day', models.DateField()),
                ('rent_income', models.PositiveIntegerField()),
                ('stipend_income', models.PositiveIntegerField()),
                ('other_income', models.PositiveIntegerField()),
                ('total_income', models.PositiveIntegerField()),
                ('lindex_rate', models.PositiveIntegerField()),
                ('server_expense_usd', models.DecimalField(decimal_places=2, max_digits=8)),
                ('server_expense', models.PositiveIntegerField()),
                ('tier_expense_usd', models.DecimalField(decimal_places=2, max_digits=8)),
                ('tier_expense', models.PositiveIntegerField()),
                ('rent_expense', models.PositiveIntegerField()),
                ('upload_expense', models.PositiveIntegerField()),
                ('other_expense', models.PositiveIntegerField()),
                ('total_expense', models.PositiveIntegerField()),
                ('last_month_budget', models.IntegerField()),
                ('last_month_expense', models.IntegerField()),
                ('last_month_shortfall', models.IntegerField()),
                ('next_month_net_budget', models.IntegerField()),
                ('next_month_gross_budget', models.IntegerField()),
                ('days_in_next_month', models.PositiveSmallIntegerField()),
                ('next_month_daily_budget', models.IntegerField()),
                ('sale_count', models.PositiveIntegerField()),
                ('sales_income', models.PositiveIntegerField()),
                ('avg_sale_revenue', models.FloatField()),
                ('unique_seller_count', models.PositiveIntegerField()),
                ('unpack_count', models.PositiveIntegerField()),
                ('unique_outfit_count', models.PositiveIntegerField()),
                ('total_dividend', models.IntegerField()),
                ('dividend_per_garment', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Outfit',
            fields=[
                ('outfit_id', models.UUIDField(primary_key=True, serialize=False)),
                ('first_seen_time', models.DateTimeField(auto_now_add=True)),
                ('box_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('debit', models.PositiveIntegerField()),
                ('credit', models.PositiveIntegerField()),
                ('time', models.DateTimeField()),
                ('end_balance', models.PositiveIntegerField()),
                ('region', models.CharField(max_length=32)),
                ('order_id', models.BigIntegerField(null=True)),
                ('classification', models.CharField(choices=[('I', 'Income'), ('E', 'Expense'), ('T', 'Transfer')], max_length=1)),
                ('category', models.CharField(choices=[('SaleI', 'Sale'), ('RentI', 'Rental Income'), ('StipI', 'Stipend'), ('I', 'Other Income'), ('TierE', 'Tier Payment'), ('RentE', 'Rental Expense'), ('UpE', 'Upload Fee'), ('E', 'Other Expense'), ('Div', 'Dividend'), ('CapI', 'Capital Increase'), ('CapD', 'Capital Decrease')], max_length=5)),
                ('fiscal_day', models.DateField()),
                ('grid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sl_profile.Grid')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sl_profile.Resident')),
            ],
            options={
                'db_table': 'payroll_transaction_log',
            },
        ),
        migrations.CreateModel(
            name='UnpackEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prim_name', models.CharField(max_length=64)),
                ('slurl', models.URLField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('fiscal_day', models.DateField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator_of_unpack', to='sl_profile.Resident')),
                ('grid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sl_profile.Grid')),
            ],
            options={
                'db_table': 'payroll_unpack_log',
            },
        ),
        migrations.CreateModel(
            name='MyDayLedger',
            fields=[
                ('dayledger_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='payroll.DayLedger')),
                ('my_sale_count', models.PositiveIntegerField(default=0)),
                ('my_total_distribution', models.PositiveIntegerField(default=0)),
                ('my_avg_distribution', models.FloatField(default=0)),
                ('my_total_unpack_count', models.PositiveIntegerField(default=0)),
                ('my_sales_unpack_count', models.PositiveIntegerField(default=0)),
                ('my_unpack_sale_ratio', models.FloatField(default=0)),
                ('my_garment_count', models.PositiveIntegerField(default=0)),
                ('my_dividend', models.PositiveIntegerField(default=0)),
            ],
            options={
                'managed': False,
            },
            bases=('payroll.dayledger',),
        ),
        migrations.CreateModel(
            name='MyMonthLedger',
            fields=[
                ('monthledger_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='payroll.MonthLedger')),
                ('my_sale_count', models.PositiveIntegerField(default=0)),
                ('my_total_distribution', models.PositiveIntegerField(default=0)),
                ('my_avg_distribution', models.FloatField(default=0)),
                ('my_total_unpack_count', models.PositiveIntegerField(default=0)),
                ('my_sales_unpack_count', models.PositiveIntegerField(default=0)),
                ('my_unpack_sale_ratio', models.FloatField(default=0)),
                ('my_dividend', models.PositiveIntegerField(default=0)),
            ],
            options={
                'managed': False,
            },
            bases=('payroll.monthledger',),
        ),
        migrations.CreateModel(
            name='OutfitProfile',
            fields=[
                ('outfit_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='payroll.Outfit')),
                ('slurl', models.URLField(blank=True)),
                ('marketplace_url', models.URLField(blank=True)),
                ('price', models.PositiveIntegerField(default=0)),
            ],
            bases=('payroll.outfit',),
        ),
        migrations.AddField(
            model_name='unpackevent',
            name='outfit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.Outfit'),
        ),
        migrations.AddField(
            model_name='unpackevent',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_of_unpack', to='sl_profile.Resident'),
        ),
        migrations.AddField(
            model_name='outfit',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sl_profile.Resident'),
        ),
        migrations.AddField(
            model_name='monthledger',
            name='grid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sl_profile.Grid'),
        ),
        migrations.AddField(
            model_name='dayledger',
            name='grid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sl_profile.Grid'),
        ),
        migrations.AddIndex(
            model_name='unpackevent',
            index=models.Index(fields=['grid', 'fiscal_day', 'creator'], name='payroll_unp_grid_id_1c3211_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['grid', 'fiscal_day', 'resident'], name='payroll_tra_grid_id_efd639_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='monthledger',
            unique_together=set([('grid', 'first_day')]),
        ),
        migrations.AlterUniqueTogether(
            name='dayledger',
            unique_together=set([('grid', 'fiscal_day')]),
        ),
    ]
