# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-26 04:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BodyPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=64, unique=True)),
                ('modifies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mods', related_query_name='mod', to='delivery.BodyPart')),
            ],
        ),
        migrations.CreateModel(
            name='Garment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateField(auto_now_add=True)),
                ('date_removed', models.DateField(blank=True, null=True)),
                ('avatar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avatar_garments', related_query_name='avatar_garment', to='delivery.BodyPart')),
                ('mods', models.ManyToManyField(related_name='mod_garments', related_query_name='mod_garment', to='delivery.BodyPart')),
            ],
        ),
        migrations.CreateModel(
            name='GarmentAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('garment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', related_query_name='asset', to='delivery.Garment')),
            ],
        ),
        migrations.CreateModel(
            name='GarmentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='garment',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.GarmentType'),
        ),
    ]
