# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 04:55
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sl_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=64, unique=True)),
                ('modifies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mods', related_query_name='mod', to='delivery.BodyPart')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_id', models.UUIDField()),
                ('box_name', models.CharField(max_length=64)),
                ('region_name', models.CharField(max_length=32)),
                ('region_pos', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), max_length=2, size=None)),
                ('region_hostname', models.URLField()),
                ('box_pos', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), max_length=3, size=None)),
                ('box_rot', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), max_length=4, size=None)),
                ('box_vel', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), max_length=3, size=None)),
                ('slurl', models.URLField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('fiscal_day', models.DateField()),
                ('avatar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.BodyPart')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator_of_unpack', to='sl_profile.Resident')),
                ('grid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sl_profile.Grid')),
                ('mods', models.ManyToManyField(related_name='_deliveryrequest_mods_+', to='delivery.BodyPart')),
            ],
            options={
                'db_table': 'delivery_request_log',
            },
        ),
        migrations.CreateModel(
            name='Garment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateField(auto_now_add=True)),
                ('date_removed', models.DateField(blank=True, null=True)),
                ('avatar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.BodyPart')),
                ('mods', models.ManyToManyField(related_name='_garment_mods_+', to='delivery.BodyPart')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GarmentAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('garment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', related_query_name='asset', to='delivery.Garment')),
            ],
        ),
        migrations.CreateModel(
            name='GarmentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Outfit',
            fields=[
                ('outfit_id', models.UUIDField(primary_key=True, serialize=False)),
                ('first_seen_time', models.DateTimeField(auto_now_add=True)),
                ('box_name', models.CharField(max_length=64)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sl_profile.Resident')),
            ],
        ),
        migrations.AddField(
            model_name='garment',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.GarmentType'),
        ),
        migrations.AddField(
            model_name='deliveryrequest',
            name='outfit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.Outfit'),
        ),
        migrations.AddField(
            model_name='deliveryrequest',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_of_unpack', to='sl_profile.Resident'),
        ),
        migrations.AddIndex(
            model_name='deliveryrequest',
            index=models.Index(fields=['grid', 'fiscal_day', 'creator'], name='delivery_re_grid_id_67cd04_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryrequest',
            index=models.Index(fields=['grid', 'creator', 'fiscal_day'], name='delivery_re_grid_id_58ee63_idx'),
        ),
    ]
