# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 17:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryrequest',
            name='extra_inventory_count',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliveryrequest',
            name='inventory_count',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deliveryrequest',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='sl_profile.Resident'),
        ),
        migrations.AlterField(
            model_name='deliveryrequest',
            name='outfit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='delivery.Outfit'),
        ),
        migrations.AlterField(
            model_name='deliveryrequest',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='sl_profile.Resident'),
        ),
    ]
