# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-10 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_auto_20170910_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='outfit',
            name='garments',
            field=models.ManyToManyField(to='delivery.GarmentType'),
        ),
    ]
