# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-10 17:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0006_outfit_garments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodypart',
            name='modifies',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mods', related_query_name='mod', to='delivery.BodyPart'),
        ),
    ]
