# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sl_profile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='resident',
            name='sl_profile__key_12017a_idx',
        ),
        migrations.RemoveIndex(
            model_name='resident',
            name='sl_profile__user_na_2dd07d_idx',
        ),
        migrations.AddField(
            model_name='grid',
            name='hostname_suffix',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resident',
            name='key',
            field=models.UUIDField(db_index=True),
        ),
    ]
