# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sl_profile', '0002_auto_20170904_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grid',
            name='hostname_suffix',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
