# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 01:55
from __future__ import unicode_literals

from django.db import migrations


def create_grids(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    Grid = apps.get_model("sl_profile", "Grid")
    db_alias = schema_editor.connection.alias
    Grid.objects.using(db_alias).bulk_create([
        Grid(name="Second Life", nick="agni", region_domain="agni.lindenlab.com"),
        Grid(name="Second Life Beta", nick="aditi", region_domain="aditi.lindenlab.com"),
        Grid(name="OSGrid", nick="osgrid", region_domain="osgrid.org"),
        Grid(name="InWorldz", nick="inworldz", region_domain=None),
        Grid(name="3RD Rock Grid", nick="3RG", region_domain="3rdrockgrid.com"),
        Grid(name="Craft World", nick="craft", region_domain="craft-world.org"),
        Grid(name="DigiWorldZ Grid", nick="DWG", region_domain="digiworldz.com"),
        Grid(name="Island Oasis", nick="island_oasis", region_domain="IOGRIDE-SERVER"),
        Grid(name="Kitely", nick="Kitely", region_domain=None),
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('sl_profile', '0004_auto_20170905_0120'),
    ]

    operations = [
        migrations.RunPython(create_grids),
    ]
