# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 04:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sl_profile', '0001_initial'),
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyPartInterest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.BooleanField(default=False)),
                ('watch', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='BodyPartProfile',
            fields=[
                ('bodypart_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='delivery.BodyPart')),
                ('remote_image_url', models.URLField()),
                ('image', models.ImageField(upload_to='')),
            ],
            options={
                'abstract': False,
            },
            bases=('delivery.bodypart', models.Model),
        ),
        migrations.CreateModel(
            name='CrowdSourcedBooleanFieldVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_id', models.PositiveIntegerField()),
                ('version', models.PositiveIntegerField(default=0)),
                ('votes', models.PositiveIntegerField(default=0)),
                ('editor_key', models.UUIDField()),
                ('editor_ip', models.GenericIPAddressField()),
                ('edited', models.DateTimeField(auto_now_add=True)),
                ('value', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CrowdSourcedCharFieldVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_id', models.PositiveIntegerField()),
                ('version', models.PositiveIntegerField(default=0)),
                ('votes', models.PositiveIntegerField(default=0)),
                ('editor_key', models.UUIDField()),
                ('editor_ip', models.GenericIPAddressField()),
                ('edited', models.DateTimeField(auto_now_add=True)),
                ('value', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CrowdSourcedPositiveIntegerFieldVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_id', models.PositiveIntegerField()),
                ('version', models.PositiveIntegerField(default=0)),
                ('votes', models.PositiveIntegerField(default=0)),
                ('editor_key', models.UUIDField()),
                ('editor_ip', models.GenericIPAddressField()),
                ('edited', models.DateTimeField(auto_now_add=True)),
                ('value', models.PositiveIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GarmentCompatibility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nsweb.BodyPartProfile')),
                ('compatible', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='compatibility_of', to='nsweb.CrowdSourcedBooleanFieldVersion')),
            ],
        ),
        migrations.CreateModel(
            name='GarmentProfile',
            fields=[
                ('garment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='delivery.Garment')),
                ('remote_image_url', models.URLField()),
                ('image', models.ImageField(upload_to='')),
                ('source_file', models.FileField(upload_to='')),
                ('compatabilities', models.ManyToManyField(related_name='compatibilities', through='nsweb.GarmentCompatibility', to='nsweb.BodyPartProfile')),
            ],
            options={
                'abstract': False,
            },
            bases=('delivery.garment', models.Model),
        ),
        migrations.CreateModel(
            name='OutfitProfile',
            fields=[
                ('outfit_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='delivery.Outfit')),
                ('slurl', models.URLField(blank=True)),
                ('marketplace_url', models.URLField(blank=True)),
                ('price', models.PositiveIntegerField(default=0)),
            ],
            bases=('delivery.outfit',),
        ),
        migrations.CreateModel(
            name='ResidentProfile',
            fields=[
                ('resident_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sl_profile.Resident')),
                ('remote_image_url', models.URLField()),
                ('image', models.ImageField(upload_to='')),
                ('display_name', models.CharField(max_length=64)),
                ('marketplace_store_url', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_store_url_of', to='nsweb.CrowdSourcedCharFieldVersion')),
                ('store_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='store_name_of', to='nsweb.CrowdSourcedCharFieldVersion')),
                ('store_slurl', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='store_slurl_of', to='nsweb.CrowdSourcedCharFieldVersion')),
            ],
            options={
                'abstract': False,
            },
            bases=('sl_profile.resident', models.Model),
        ),
        migrations.AddField(
            model_name='garmentprofile',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nsweb.ResidentProfile'),
        ),
        migrations.AddField(
            model_name='garmentcompatibility',
            name='garment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nsweb.GarmentProfile'),
        ),
        migrations.AddIndex(
            model_name='crowdsourcedpositiveintegerfieldversion',
            index=models.Index(fields=['field_id', 'version'], name='nsweb_crowd_field_i_b86b21_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='crowdsourcedpositiveintegerfieldversion',
            unique_together=set([('field_id', 'version')]),
        ),
        migrations.AddIndex(
            model_name='crowdsourcedcharfieldversion',
            index=models.Index(fields=['field_id', 'version'], name='nsweb_crowd_field_i_6bf7d9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='crowdsourcedcharfieldversion',
            unique_together=set([('field_id', 'version')]),
        ),
        migrations.AddIndex(
            model_name='crowdsourcedbooleanfieldversion',
            index=models.Index(fields=['field_id', 'version'], name='nsweb_crowd_field_i_631611_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='crowdsourcedbooleanfieldversion',
            unique_together=set([('field_id', 'version')]),
        ),
        migrations.AddField(
            model_name='bodypartprofile',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nsweb.ResidentProfile'),
        ),
        migrations.AddField(
            model_name='bodypartprofile',
            name='marketplace_url',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_url_of', to='nsweb.CrowdSourcedCharFieldVersion'),
        ),
        migrations.AddField(
            model_name='bodypartprofile',
            name='price',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='price_of', to='nsweb.CrowdSourcedPositiveIntegerFieldVersion'),
        ),
        migrations.AddField(
            model_name='bodypartprofile',
            name='slurl',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='slurl_of', to='nsweb.CrowdSourcedCharFieldVersion'),
        ),
        migrations.AddField(
            model_name='bodypartinterest',
            name='body_part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.BodyPart'),
        ),
        migrations.AddField(
            model_name='bodypartinterest',
            name='resident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sl_profile.Resident'),
        ),
    ]
